#ifndef ENEMY_SCORE_H
#define ENEMY_SCORE_H

#define ENEMY_SCORE_DRAGOON				15
#define ENEMY_SCORE_GUARDIAN			20
#define ENEMY_SCORE_MINION_1			5
#define ENEMY_SCORE_MINION_2			10
#define ENEMY_SCORE_MINION_EGG			0
#define ENEMY_SCORE_PATROLLER			15
#define ENEMY_SCORE_PROXIMITY_DRONE		20
#define ENEMY_SCORE_SENTRY				10
#define ENEMY_SCORE_SWEEPER				10
#define ENEMY_SCORE_E02ROVER			15
#define ENEMY_SCORE_MB01GOLEM			30
#define ENEMY_SCORE_THE_EYE				20
#define ENEMY_SCORE_SPIKE_SHIP			20
#define ENEMY_SCORE_E01SENSOR			15

#endif