#ifndef KEYWORDS_H
#define KEYWORDS_H

enum Keyword {
	KW_NONE,
	KW_ID, KW_X, KW_Y, KW_INTERVAL, KW_COUNT,
	KW_START_ASSET, KW_CLOSE_ASSET, KW_PATH, KW_START_CLONE, KW_CLOSE_CLONE, KW_ROTATION_ANGLE, KW_FLIP_X, KW_FLIP_Y, KW_ALPHA_BLEND, KW_IS_PRIORITISED,
	KW_START_BB, KW_CLOSE_BB, KW_MIN_X, KW_MIN_Y, KW_MAX_X, KW_MAX_Y,
	KW_NAME, KW_WIDTH, KW_HEIGHT, KW_MAX_SPEED, KW_CAUTION_DISTANCE, KW_SHOOTING_SHARPNESS, KW_SPECIAL_THROW, KW_SECONDARY_ABILITY,
	KW_START_WAVE, KW_CLOSE_WAVE, KW_START_ENEMY, KW_CLOSE_ENEMY, KW_START_SHIP, KW_CLOSE_SHIP, KW_START_PICKUP, KW_CLOSE_PICKUP, KW_PICKUP_START_MOVES, KW_PICKUP_CLOSE_MOVES, KW_START_PLAYER_POSITION, KW_CLOSE_PLAYER_POSITION,
	KW_RESPAWN_COUNT, 
	KW_START_GRID_OFFSET, KW_CLOSE_GRID_OFFSET
};

#endif